### Sample configuration for use with "rake db:remote" using ERB to eliminate duplication:

# SSH username to login as:
username: pdxruby

# Hostname to log into with SSH:
hostname: pdxruby.org

# Base directory of site:
<% base_dir = '/var/www/pdxruby' %>

# Filename of backup to create on server:
<% backup_file = base_dir+'/shared/db/database.sql' %>

# Command to run to create database dump:
backup_command: cd <%= base_dir %>/current && rake --silent db:raw:dump FILE=<%= backup_file %> RAILS_ENV=production

# File to download using RSYNC:
backup_file: <%= backup_file %>
