### Sample configuration for use with "rake db:remote", see also "db_remote~sample-erb.yml":

# SSH username to login as:
username: pdxruby

# Hostname to log into with SSH:
hostname: pdxruby.org

# Command to run to create database dump:
backup_command: cd /var/www/pdxruby/current && rake --silent db:raw:dump FILE=/var/www/pdxruby/shared/db/database.sql RAILS_ENV=production

# File to download using RSYNC:
backup_file: /var/www/pdxruby/shared/db/database.sql
